name: Close Issues with Done Label

on:
  issues:
    types:
      - labeled

jobs:
  close_issue_if_done:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the label is "Done"
        if: contains(github.event.label.name, 'Done')
        run: |
          echo "The issue is labeled 'Done', proceeding to close the issue."
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
            -d '{"state": "closed"}'
